# Generated by Django 5.0.6 on 2024-06-06 12:36

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('reserve_quantity', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medication',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_prefix', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('identification_number', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_no', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=6)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('drug_allergy', models.TextField(default='None')),
                ('face_encodings', models.CharField(blank=True, max_length=3000, null=True)),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('past_medical_history', models.TextField(blank=True, null=True)),
                ('consultation', models.TextField(blank=True, null=True)),
                ('plan', models.TextField(blank=True, null=True)),
                ('referred_for', models.TextField(blank=True, null=True)),
                ('referral_notes', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_create', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consults',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('consult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.consult')),
            ],
            options={
                'db_table': 'diagnosis',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('order_status', models.CharField(max_length=255)),
                ('consult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.consult')),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.medication')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patient')),
            ],
            options={
                'db_table': 'visits',
            },
        ),
        migrations.AddField(
            model_name='consult',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.visit'),
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('systolic', models.IntegerField(default=0)),
                ('diastolic', models.IntegerField(default=0)),
                ('temperature', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('diabetes_mellitus', models.TextField(blank=True, default="Haven't Asked / Not Applicable", null=True)),
                ('heart_rate', models.IntegerField(default=0)),
                ('urine_test', models.TextField(blank=True, null=True)),
                ('hemocue_count', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('blood_glucose', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('left_eye_degree', models.TextField(blank=True, null=True)),
                ('right_eye_degree', models.TextField(blank=True, null=True)),
                ('left_eye_pinhole', models.TextField(blank=True, null=True)),
                ('right_eye_pinhole', models.TextField(blank=True, null=True)),
                ('others', models.TextField(blank=True, null=True)),
                ('visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.visit')),
            ],
            options={
                'db_table': 'vitals',
            },
        ),
    ]
