# Generated by Django 5.0.6 on 2024-09-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='offline_file',
            field=models.FileField(null=True, upload_to='offline_files/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
