# Generated by Django 5.0.6 on 2024-08-20 06:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bs2',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='poor',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='patient',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
