# Generated by Django 5.0.6 on 2024-08-15 14:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="medication_updates",
        ),
        migrations.CreateModel(
            name="MedicationReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_changed", models.IntegerField(default=0)),
                ("quantity_remaining", models.IntegerField(default=0)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("order_status", models.CharField(max_length=255)),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_create_medication_review",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.medication",
                    ),
                ),
            ],
            options={
                "db_table": "medication_review",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="medication_review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="api.medicationreview",
            ),
        ),
        migrations.DeleteModel(
            name="MedicationUpdates",
        ),
    ]
