# Generated by Django 5.0.6 on 2024-09-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient_bs2_patient_poor_alter_patient_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
