# Generated by Django 5.0.6 on 2024-08-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_patient_bs2_patient_poor_alter_patient_contact_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="offline_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="offline_pictures"
            ),
        ),
    ]
