# Generated by Django 5.0.6 on 2024-10-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient_offline_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
