# Generated by Django 5.0.6 on 2024-10-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient_offline_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sabai',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
