# Generated by Django 5.0.6 on 2024-08-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_order_medication_updates_medicationreview_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicationreview",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("APPROVED", "Approved"),
                    ("PENDING", "Pending"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=255,
            ),
        ),
    ]
