# Generated by Django 5.0.6 on 2024-09-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient_bs2_patient_poor_alter_patient_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='gross_motor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='heart',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='hernial_orifices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='lungs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='menarche',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='menarche_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='oral_cavity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='pallor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='pubarche',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='pubarche_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='red_reflex',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='scoliosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='thelarche',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='thelarche_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
