# Generated by Django 5.0.6 on 2024-06-13 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_medication_reserve_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='picture',
        ),
    ]
