# Generated by Django 5.0.6 on 2024-11-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_medication_quantity"),
        ("api", "0003_patient_sabai"),
    ]

    operations = []
