# Generated by Django 5.0.6 on 2024-08-15 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_order_medication_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="medication_updates",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_set",
                to="api.medicationupdates",
            ),
        ),
    ]
