# Generated by Django 5.0.6 on 2024-12-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20241104_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitals',
            old_name='blood_glucose',
            new_name='blood_glucose_non_fasting',
        ),
    ]
