# Generated by Django 5.0.6 on 2024-12-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20241104_2310'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicationreview',
            index=models.Index(fields=['order_status'], name='medication__order_s_c536ae_idx'),
        ),
    ]
