# Generated by Django 5.0.6 on 2024-07-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_patient_contact_no_alter_patient_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
