# Generated by Django 5.0.6 on 2024-06-13 03:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='picture',
            field=cloudinary.models.CloudinaryField(default=12, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
