# Generated by Django 5.0.6 on 2024-09-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_vitals_gross_motor_alter_vitals_menarche_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='menarche',
            field=models.TextField(blank=True, default="Haven't Asked / Not Applicable", null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='pubarche',
            field=models.TextField(blank=True, default="Haven't Asked / Not Applicable", null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='thelarche',
            field=models.TextField(blank=True, default="Haven't Asked / Not Applicable", null=True),
        ),
    ]
