# Generated by Django 5.0.6 on 2025-06-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_blood_glucose_vitals_blood_glucose_non_fasting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
