# Generated by Django 5.0.6 on 2024-09-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_vitals_menarche_alter_vitals_pubarche_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='testicular_growth',
            field=models.TextField(blank=True, default="Haven't Asked / Not Applicable", null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='testicular_growth_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='voice_change',
            field=models.TextField(blank=True, default="Haven't Asked / Not Applicable", null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='voice_change_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
