# Generated by Django 5.0.6 on 2025-06-11 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_medication_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Glasses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "left_glasses_degree",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "right_glasses_degree",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.visit",
                    ),
                ),
            ],
            options={
                "db_table": "glasses_prescription",
            },
        ),
    ]
