# Generated by Django 5.0.6 on 2025-06-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_referrals"),
    ]

    operations = [
        migrations.RenameField(
            model_name="referrals",
            old_name="referral_comments",
            new_name="referral_notes",
        ),
        migrations.AddField(
            model_name="referrals",
            name="referral_outcome",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="referrals",
            name="referred_for",
            field=models.TextField(blank=True, null=True),
        ),
    ]
