# Generated by Django 5.0.6 on 2024-06-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_medication_remarks_alter_consult_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='blood_glucose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='hemocue_count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
