# Generated by Django 5.0.6 on 2024-07-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_patient_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bs2',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='poor',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
