# Generated by Django 5.0.6 on 2025-06-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_glasses"),
        ("api", "0007_rename_referral_comments_referrals_referral_notes_and_more"),
    ]

    operations = []
