# Generated by Django 5.0.6 on 2024-07-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_vitals_diastolic_alter_vitals_heart_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='diastolic',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='heart_rate',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='systolic',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
    ]
