# Generated by Django 5.0.6 on 2025-07-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_merge_20250616_0311"),
    ]

    operations = [
        migrations.AddField(
            model_name="glasses",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="left_astigmatism",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="vitals",
            name="right_astigmatism",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
