# Generated by Django 5.0.6 on 2024-07-01 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consult",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctor_create",
                to="api.customuser",
            ),
        ),
    ]
