# Generated by Django 5.0.6 on 2024-07-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='village_prefix',
            field=models.CharField(max_length=5),
        ),
    ]
