# Generated by Django 5.0.6 on 2025-08-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_customuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("village_name", models.CharField(max_length=20, unique=True)),
                ("colour_code", models.CharField(max_length=20)),
                ("is_hidden", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "village",
            },
        ),
    ]
