# Generated by Django 5.0.6 on 2025-08-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_village"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
