# Generated by Django 5.0.6 on 2025-10-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_populate_initial_villages"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="warning_quantity",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
