# Generated by Django 5.0.6 on 2025-10-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_medication_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="auth0_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
