# Generated by Django 5.0.6 on 2025-10-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_customuser_auth0_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
