# Generated by Django 5.0.6 on 2025-12-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_customuser_is_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="is_image_edited",
            field=models.BooleanField(default=False),
        ),
    ]
