# Generated by Django 5.0.6 on 2025-11-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_customuser_is_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
