# Generated by Django 5.0.6 on 2025-12-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_file_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="isCurrentStock",
            field=models.BooleanField(default=True),
        ),
    ]
