# Generated by Django 5.0.6 on 2025-11-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_file_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="category",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="details",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
