# Generated by Django 5.0.6 on 2025-12-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_medication_iscurrentstock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medication",
            old_name="isCurrentStock",
            new_name="is_current_stock",
        ),
    ]
