# Generated by Django 5.0.6 on 2025-12-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_rename_iscurrentstock_medication_is_current_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="to_get_report",
            field=models.BooleanField(default=False),
        ),
    ]
