# Generated by Django 5.0.6 on 2025-12-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_image_edited_trigger_modification"),
        ("api", "0021_patient_to_get_report"),
    ]

    operations = []
