# Generated by Django 5.0.6 on 2025-12-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_merge_20251206_1956"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitals",
            name="hbA1c",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
