# Generated by Django 5.0.6 on 2025-12-07 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_vitals_hba1c"),
    ]

    operations = [
        migrations.AddField(
            model_name="consult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
