# Generated by Django 5.0.6 on 2025-12-08 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_consult_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consult",
            name="created_at",
        ),
    ]
